FROM python:3.11

WORKDIR /app

COPY src/services/rag_service/requirements.txt ./src/requirements.txt

RUN pip install --no-cache-dir -r ./src/requirements.txt

COPY src/services/rag_service /app/src
COPY src/config.yaml /app/src/config.yaml

CMD ["uvicorn", "src.app.main:app", "--host", "0.0.0.0", "--port", "1299"]