services:
  neo4j:
    image: neo4j:5.26.9
    container_name: leetllama_neo4j
    restart: "no"
    networks:
      - leetllama_net
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/graph_volume:/data

networks:
  default:
    name: leetllama_net